In [174]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from math import *
import scipy.stats
from pandas import *
#import scipy.integrate as integrate
from scipy.integrate import quad
import seaborn as sns
import scipy as s
import warnings
warnings.filterwarnings("ignore")
from mpl_toolkits import mplot3d

import plotly.offline as pyoff
import plotly.graph_objs as go
import plotly.graph_objects as go
from scipy import linalg 


In [175]:
def jump_distribution_full(x_value,mu,sigma_jump,step_x):
    lower = x_value - step_x/2.0
    upper = x_value + step_x/2.0
    #print(lower,upper)
    def normal_distribution_function(x):
        value = scipy.stats.norm.pdf(x,mu,sigma_jump)
        return value
    res, err = quad(normal_distribution_function, lower, upper)
    return res  #output is a vector of the average densities around the regions of each value in the vector x


In [178]:
x0 = -10.0
xn = 10.0
xsteps = 1000
dx = (xn-x0)/xsteps
x = np.arange(x0, xn+dx, dx) #last x value is x = 99 
#print(x,len(x),dx)

In [179]:
t0 = 0.0
tn = 1.0
tsteps = 100
dt = (tn-t0)/tsteps
t = np.arange(t0, tn+dt, dt) #last time value is t = 999.9
r = dt / (dx**2) # ensure r < 1
print(dt)
#print(t,r,len(t),tsteps,dt)

0.01


In [180]:
def a_coeff(x_value, sigma, kappa, theta, jump_rate):
    coefficient = jump_rate + (sigma**2)/(dx**2)
    return coefficient

def b_coeff(x_value, sigma, kappa, theta, jump_rate):
    coefficient_2 = 0.5*(sigma**2)*(1/dx**2) + 0.5*(1/dx)*kappa*(theta-x_value)
    return coefficient_2

def c_coeff(x_value, sigma, kappa, theta, jump_rate):
    coefficient_3 = 0.5*(sigma**2)*(1/dx**2) - 0.5*(1/dx)*kappa*(theta-x_value)
    return coefficient_3   

In [181]:
def M_matrix(x,sigma,kappa, theta, jump_rate):
    M = np.zeros(shape=(len(x),len(x)))
    for i in range(0,len(x)):
        if x[i] <= 0 or x[i] >= 1:
            M[i,i] = 1.0
        else:
            a_coefficient = a_coeff(x[i], sigma, kappa, theta, jump_rate)
            b_coefficient = b_coeff(x[i], sigma, kappa, theta, jump_rate)
            c_coefficient = c_coeff(x[i], sigma, kappa, theta, jump_rate)
            if a_coefficient < 0 or b_coefficient < 0 or c_coefficient <0:
                print('Error')
            M[i,(i-1):(i+2)] = [-dt*c_coefficient, 1+dt*a_coefficient, -dt*b_coefficient]

    return M

In [182]:
##accept_x = np.where((x>=0) & (x<=1))[0]
#accept_x

In [183]:
#M_1 = M_matrix(x,0.1,0.7,1.0,1.0)
#M_inv = np.linalg.inv(M_1)
#DataFrame(M_1[50:62,50:62])

In [184]:
def N_matrix(x, jump_rate, N, mu, sigma_jump, step_x):
    N_m = np.zeros(shape=(len(x),len(x)))
    positions = np.arange(int(-N/2+1),int(N/2),1)
    for i in range(0,(len(x))):
        if x[i] > 0.0 and x[i] < 1.0:
            for j in positions: 
                x_jump = step_x*j
                integral = jump_distribution_full(x_jump, mu, sigma_jump, step_x)
                if (i+j) >= 0 and (i+j) <= (len(x)-1):
                    #print(j)
                    N_m[i,i+j] = jump_rate*dt*integral
            N_m[i,i] = N_m[i,i]+1
    return N_m

In [185]:
#N_try = N_matrix(x, 1.0,4,0.0,0.1,dx)
#DataFrame(N_try[50:62,50:62])

In [186]:
#N_try = N_matrix(x, 1.0,4,0.0,0.1,dx)
#DataFrame(N_try[0:10, 0:10])

In [187]:
#def IC_matrix(x, sigma, kappa, theta, jump_rate, mu, sigma_jump, step_x, phi_0, phi_N):
#    b = np.zeros(len(x)-2)
#    B = np.zeros(len(x)-2)
#    b_coefficient = b_coeff(x[1], sigma, kappa, theta, jump_rate)
#    c_coefficient = c_coeff(x[len(x)-2], sigma, kappa, theta, jump_rate)
#    b[0] = c_coefficient*dt*phi_0
#    b[len(x)-3] = b_coefficient*dt*phi_N
    #print(b)
#    jump_0 = jump_distribution_full(-1*dx, mu, sigma_jump, step_x)
#    jump_N = jump_distribution_full(1*dx, mu, sigma_jump, step_x)
#    B[0] = jump_rate*dt*jump_0
#    B[len(x)-3] = jump_rate*dt*jump_N
    
#    IC = b+B
#    return IC

In [188]:
#IC_matrix(x,1,1,1,1,0,1,dx,0,1)

In [189]:
b = np.zeros(len(x))
b[x>=1.0] = 1.0

In [190]:
phi_matrix = np.zeros(shape=(len(x), len(t)))
phi_matrix[:,0] = 1.0 * (x>0.0)
phi_matrix[len(x)-1,:] = 1.0
#DataFrame(phi_matrix)

In [221]:
sigma_choice = 0.5
kappa_choice = 0.5
theta_choice = 0.3
jump_rate_choice = 1.0
N_choice = 4
mu_choice = 0.0
sigma_jump_choice = 0.5

M = M_matrix(x,sigma = sigma_choice,kappa = kappa_choice, theta = theta_choice, jump_rate = jump_rate_choice)
#print(DataFrame(M[13:28,13:28]))
N_mat = N_matrix(x, jump_rate = jump_rate_choice, N = N_choice, mu = mu_choice, sigma_jump = sigma_jump_choice, step_x=dx)
#print(DataFrame(N_mat[13:28,13:28]))
#print(b[0])

if sigma_choice**2 >= np.max(np.abs(dx*kappa_choice*(theta_choice-x))):
    for time in range(1, len(t)): 
        phi_matrix[:,time] = np.linalg.inv(M).dot(N_mat.dot(phi_matrix[:,time-1]) + b)
        #print(DataFrame(np.dot(np.linalg.inv(M), M)))
        #phi_matrix[:,time] = linalg.solve(M, N_mat.dot(phi_matrix[:,time-1]) + b )
        
else:
    print('Stability conditions may not be satisfied')
    

In [222]:
accept_x = np.where((x>=0) & (x<=1))[0]
accept_x

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550], dtype=int64)

In [223]:
phi_matrix[26,] 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
for i in range(0,len(phi_matrix)-1):
    print(np.min(phi_matrix[i+1,:] - phi_matrix[i,:]))

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [64]:
for i in range(0,len(t)-1):
    print(np.max(phi_matrix[:,i+1] - phi_matrix[:,i]))

1.360308049807529e-17
0.0
1.7291167724525608e-18
1.6170948666546702e-19
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [224]:
def survival(space,time):
    return phi_matrix[space, time]


In [225]:
X = accept_x #np.arange(50,65,1)
T = np.arange(0,len(t),1)
X, T = np.meshgrid(X, T)
Phi = survival(X,T)

data=go.Surface(z=Phi, x=x0+dx*X, y=t0+dt*T)

layout = go.Layout(scene = dict(
                    xaxis_title='Initial Position',
                    yaxis_title='Maturity',
                    zaxis_title='Survival Probability'))

fig = go.Figure(data=[data], layout=layout)
pyoff.plot(fig)

'temp-plot.html'

In [226]:
surv = DataFrame(phi_matrix)

In [227]:
surv['initial_pos'] = x #x0+dx*X[1]

In [228]:
times= DataFrame(t)
time= times[0]

In [229]:
surv.append(time)

0     1     2     3     4     5     6     7     8     9  ...    92  \
0     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
1     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
2     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
3     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
4     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
997   1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  ...  1.00   
998   1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  ...  1.00   
999   1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  ...  1.00   
1000  1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  ...  1.00   
0     0.0  0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  ...  0.92   

        93    94    95    96    97    98    99  100  initial_pos  
0     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0       -10.00  
1     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0        -9.98  
2     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0        -9.96  
3     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0        -9.94  
4     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0        -9.92  
...    ...   ...   ...   ...   ...   ...   ...  ...          ...  
997   1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0         9.94  
998   1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0         9.96  
999   1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0         9.98  
1000  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0        10.00  
0     0.93  0.94  0.95  0.96  0.97  0.98  0.99  1.0          NaN  

[1002 rows x 102 columns]

In [230]:
x[550]

0.9999999999997655

In [231]:
y = np.where((x >= 0.0) & (x<= 1.02))
surv_df_non_zero = surv.iloc[y[0],]
surv_df_non_zero

0         1         2         3         4         5         6  \
501  1.0  0.431494  0.275873  0.212309  0.177789  0.155551  0.139684   
502  1.0  0.674788  0.497204  0.400433  0.341248  0.301084  0.271672   
503  1.0  0.812063  0.659215  0.555233  0.483619  0.431804  0.392443   
504  1.0  0.889580  0.771667  0.675792  0.602034  0.544912  0.499621   
505  1.0  0.933390  0.847070  0.765865  0.696795  0.639565  0.592065   
506  1.0  0.958169  0.896421  0.831033  0.770221  0.716474  0.669745   
507  1.0  0.972195  0.928151  0.876999  0.825599  0.777367  0.733488   
508  1.0  0.980142  0.948276  0.908763  0.866423  0.824496  0.784684   
509  1.0  0.984648  0.960906  0.930349  0.895937  0.860251  0.825012   
510  1.0  0.987204  0.968764  0.944813  0.916921  0.886903  0.856228   
511  1.0  0.988656  0.973619  0.954391  0.931628  0.906462  0.880014   
512  1.0  0.989481  0.976602  0.960672  0.941806  0.920619  0.897880   
513  1.0  0.989951  0.978426  0.964754  0.948773  0.930739  0.911127   
514  1.0  0.990218  0.979536  0.967387  0.953495  0.937895  0.920835   
515  1.0  0.990370  0.980210  0.969075  0.956669  0.942904  0.927873   
516  1.0  0.990457  0.980618  0.970151  0.958785  0.946379  0.932927   
517  1.0  0.990507  0.980864  0.970833  0.960187  0.948771  0.936523   
518  1.0  0.990535  0.981012  0.971264  0.961110  0.950404  0.939061   
519  1.0  0.990551  0.981101  0.971535  0.961714  0.951513  0.940839   
520  1.0  0.990560  0.981155  0.971705  0.962108  0.952261  0.942076   
521  1.0  0.990566  0.981187  0.971811  0.962363  0.952762  0.942931   
522  1.0  0.990569  0.981206  0.971877  0.962528  0.953097  0.943519   
523  1.0  0.990570  0.981217  0.971918  0.962634  0.953319  0.943922   
524  1.0  0.990571  0.981224  0.971943  0.962702  0.953466  0.944195   
525  1.0  0.990572  0.981228  0.971959  0.962746  0.953563  0.944381   
526  1.0  0.990572  0.981231  0.971969  0.962774  0.953628  0.944507   
527  1.0  0.990572  0.981232  0.971975  0.962792  0.953670  0.944593   
528  1.0  0.990573  0.981233  0.971979  0.962803  0.953699  0.944653   
529  1.0  0.990573  0.981234  0.971981  0.962812  0.953719  0.944695   
530  1.0  0.990573  0.981234  0.971983  0.962818  0.953734  0.944728   
531  1.0  0.990573  0.981235  0.971985  0.962823  0.953748  0.944757   
532  1.0  0.990573  0.981235  0.971987  0.962830  0.953762  0.944786   
533  1.0  0.990573  0.981236  0.971990  0.962838  0.953781  0.944821   
534  1.0  0.990573  0.981237  0.971995  0.962850  0.953806  0.944867   
535  1.0  0.990574  0.981240  0.972002  0.962868  0.953842  0.944933   
536  1.0  0.990574  0.981243  0.972014  0.962896  0.953898  0.945028   
537  1.0  0.990575  0.981250  0.972034  0.962940  0.953980  0.945166   
538  1.0  0.990577  0.981260  0.972065  0.963008  0.954106  0.945368   
539  1.0  0.990581  0.981279  0.972116  0.963115  0.954293  0.945663   
540  1.0  0.990588  0.981309  0.972197  0.963279  0.954573  0.946089   
541  1.0  0.990600  0.981361  0.972328  0.963531  0.954988  0.946703   
542  1.0  0.990621  0.981448  0.972536  0.963917  0.955599  0.947580   
543  1.0  0.990659  0.981594  0.972866  0.964500  0.956492  0.948823   
544  1.0  0.990728  0.981836  0.973386  0.965377  0.957784  0.950568   
545  1.0  0.990851  0.982239  0.974196  0.966682  0.959635  0.952996   
546  1.0  0.991072  0.982903  0.975449  0.968604  0.962263  0.956341   
547  1.0  0.991469  0.983990  0.977367  0.971402  0.965948  0.960900   
548  1.0  0.992185  0.985754  0.980265  0.975426  0.971056  0.967045   
549  1.0  0.993475  0.988584  0.984583  0.981128  0.978043  0.975230   
550  1.0  0.995801  0.993058  0.990910  0.989085  0.987469  0.986001   
551  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   

            7         8         9  ...        92        93        94  \
501  0.127600  0.117977  0.110060  ...  0.016466  0.016245  0.016028   
502  0.248933  0.230649  0.215507  ...  0.032546  0.032109  0.031681   
503  0.361315  0.335905  0.314636  ...  0.0482

In [232]:
accept_t = [0,10,20,30,40,50,60,70,80,90,100]

In [233]:
times = t[accept_t[1:]]
times

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [236]:
output=surv_df_non_zero.iloc[:,accept_t[1:]]
initial_pos = surv['initial_pos'][(surv['initial_pos'] >= 0.0) & (surv['initial_pos'] <= 1.02)]
output['initial_pos'] = initial_pos
survival_values = round(output,4)
survival_values = survival_values.set_index('initial_pos')
#survival_values.columns = t[accept_t]
#output
survival_values

10      20      30      40      50      60      70      80   \
initial_pos                                                                   
0.02         0.1034  0.0669  0.0501  0.0396  0.0324  0.0270  0.0228  0.0195   
0.04         0.2027  0.1318  0.0988  0.0782  0.0639  0.0532  0.0450  0.0386   
0.06         0.2965  0.1944  0.1460  0.1157  0.0946  0.0789  0.0667  0.0572   
0.08         0.3836  0.2542  0.1915  0.1521  0.1244  0.1038  0.0879  0.0754   
0.10         0.4633  0.3110  0.2352  0.1872  0.1533  0.1280  0.1085  0.0931   
0.12         0.5349  0.3646  0.2771  0.2210  0.1813  0.1515  0.1285  0.1103   
0.14         0.5984  0.4148  0.3170  0.2536  0.2083  0.1743  0.1480  0.1272   
0.16         0.6538  0.4615  0.3549  0.2847  0.2344  0.1964  0.1669  0.1436   
0.18         0.7014  0.5046  0.3907  0.3145  0.2595  0.2178  0.1853  0.1596   
0.20         0.7418  0.5441  0.4243  0.3429  0.2835  0.2384  0.2031  0.1751   
0.22         0.7756  0.5801  0.4559  0.3699  0.3066  0.2583  0.2204  0.1903   
0.24         0.8035  0.6127  0.4853  0.3955  0.3288  0.2775  0.2372  0.2051   
0.26         0.8264  0.6419  0.5127  0.4197  0.3499  0.2960  0.2535  0.2195   
0.28         0.8449  0.6680  0.5380  0.4424  0.3700  0.3138  0.2692  0.2336   
0.30         0.8596  0.6912  0.5613  0.4639  0.3892  0.3309  0.2845  0.2473   
0.32         0.8713  0.7115  0.5826  0.4839  0.4075  0.3473  0.2993  0.2607   
0.34         0.8805  0.7294  0.6022  0.5027  0.4248  0.3631  0.3137  0.2737   
0.36         0.8876  0.7449  0.6200  0.5203  0.4413  0.3782  0.3276  0.2865   
0.38         0.8931  0.7583  0.6361  0.5366  0.4568  0.3928  0.3411  0.2991   
0.40         0.8973  0.7698  0.6507  0.5518  0.4716  0.4068  0.3542  0.3114   
0.42         0.9005  0.7796  0.6639  0.5659  0.4856  0.4203  0.3670  0.3235   
0.44         0.9029  0.7880  0.6757  0.5790  0.4989  0.4332  0.3794  0.3354   
0.46         0.9047  0.7951  0.6863  0.5911  0.5115  0.4457  0.3916  0.3472   
0.48         0.9060  0.8012  0.6959  0.6024  0.5234  0.4578  0.4036  0.3589   
0.50         0.9070  0.8062  0.7044  0.6129  0.5348  0.4695  0.4153  0.3705   
0.52         0.9078  0.8105  0.7121  0.6227  0.5457  0.4810  0.4270  0.3822   
0.54         0.9083  0.8141  0.7190  0.6319  0.5562  0.4921  0.4385  0.3939   
0.56         0.9087  0.8172  0.7253  0.6405  0.5663  0.5032  0.4500  0.4057   
0.58         0.9091  0.8198  0.7310  0.6487  0.5762  0.5140  0.4616  0.4177   
0.60         0.9093  0.8221  0.7363  0.6565  0.5858  0.5249  0.4733  0.4299   
0.62         0.9095  0.8242  0.7413  0.6641  0.5953  0.5358  0.4851  0.4425   
0.64         0.9097  0.8262  0.7461  0.6715  0.6048  0.5469  0.4973  0.4554   
0.66         0.9100  0.8280  0.7508  0.6789  0.6144  0.5581  0.5098  0.4689   
0.68         0.9102  0.8300  0.7555  0.6864  0.6243  0.5698  0.5229  0.4830   
0.70         0.9105  0.8320  0.7603  0.6941  0.6344  0.5819  0.5365  0.4979   
0.72         0.9109  0.8342  0.7654  0.7021  0.6450  0.5945  0.5509  0.5135   
0.74         0.9115  0.8368  0.7709  0.7106  0.6562  0.6080  0.5661  0.5302   
0.76         0.9122  0.8398  0.7769  0.7198  0.6681  0.6223  0.5823  0.5481   
0.78         0.9131  0.8432  0.7835  0.7297  0.6810  0.6376  0.5998  0.5673   
0.80         0.9144  0.8474  0.7911  0.7406  0.6949  0.6542  0.6186  0.5880   
0.82         0.9160  0.8524  0.7996  0.7527  0.7102  0.6723  0.6391  0.6104   
0.84         0.9182  0.8583  0.8094  0.7661  0.7270  0.6921  0.6614  0.6349   
0.86         0.9211  0.8655  0.8206  0.7812  0.7456  0.7138  0.6858  0.6615   
0.88         0.9248  0.8740  0.8335  0.7982  0.7663  0.7377  0.7126  0.6907   
0.90         0.9296  0.8842  0.8484  0.8173  0.7893  0.7642  0.7421  0.7228   
0.92         0.9357  0.8964  0.8656  0.8390  0.8151  0.7936  0.7747  0.7582   
0.94         0.9435  0.9108  0.8855  0.8636  0.8440  0.8263  0.8107  0.7972   
0.96         0.9534  0.9279  0.9083  0.8915  0.8764  0.8628  0.8508  0.8403   
0.98         0.9657  0.9482  0.9347  0.9232  0.9128  0.9035  0.895

In [237]:
pd = 1-survival_values
pd

10      20      30      40      50      60      70      80   \
initial_pos                                                                   
0.02         0.8966  0.9331  0.9499  0.9604  0.9676  0.9730  0.9772  0.9805   
0.04         0.7973  0.8682  0.9012  0.9218  0.9361  0.9468  0.9550  0.9614   
0.06         0.7035  0.8056  0.8540  0.8843  0.9054  0.9211  0.9333  0.9428   
0.08         0.6164  0.7458  0.8085  0.8479  0.8756  0.8962  0.9121  0.9246   
0.10         0.5367  0.6890  0.7648  0.8128  0.8467  0.8720  0.8915  0.9069   
0.12         0.4651  0.6354  0.7229  0.7790  0.8187  0.8485  0.8715  0.8897   
0.14         0.4016  0.5852  0.6830  0.7464  0.7917  0.8257  0.8520  0.8728   
0.16         0.3462  0.5385  0.6451  0.7153  0.7656  0.8036  0.8331  0.8564   
0.18         0.2986  0.4954  0.6093  0.6855  0.7405  0.7822  0.8147  0.8404   
0.20         0.2582  0.4559  0.5757  0.6571  0.7165  0.7616  0.7969  0.8249   
0.22         0.2244  0.4199  0.5441  0.6301  0.6934  0.7417  0.7796  0.8097   
0.24         0.1965  0.3873  0.5147  0.6045  0.6712  0.7225  0.7628  0.7949   
0.26         0.1736  0.3581  0.4873  0.5803  0.6501  0.7040  0.7465  0.7805   
0.28         0.1551  0.3320  0.4620  0.5576  0.6300  0.6862  0.7308  0.7664   
0.30         0.1404  0.3088  0.4387  0.5361  0.6108  0.6691  0.7155  0.7527   
0.32         0.1287  0.2885  0.4174  0.5161  0.5925  0.6527  0.7007  0.7393   
0.34         0.1195  0.2706  0.3978  0.4973  0.5752  0.6369  0.6863  0.7263   
0.36         0.1124  0.2551  0.3800  0.4797  0.5587  0.6218  0.6724  0.7135   
0.38         0.1069  0.2417  0.3639  0.4634  0.5432  0.6072  0.6589  0.7009   
0.40         0.1027  0.2302  0.3493  0.4482  0.5284  0.5932  0.6458  0.6886   
0.42         0.0995  0.2204  0.3361  0.4341  0.5144  0.5797  0.6330  0.6765   
0.44         0.0971  0.2120  0.3243  0.4210  0.5011  0.5668  0.6206  0.6646   
0.46         0.0953  0.2049  0.3137  0.4089  0.4885  0.5543  0.6084  0.6528   
0.48         0.0940  0.1988  0.3041  0.3976  0.4766  0.5422  0.5964  0.6411   
0.50         0.0930  0.1938  0.2956  0.3871  0.4652  0.5305  0.5847  0.6295   
0.52         0.0922  0.1895  0.2879  0.3773  0.4543  0.5190  0.5730  0.6178   
0.54         0.0917  0.1859  0.2810  0.3681  0.4438  0.5079  0.5615  0.6061   
0.56         0.0913  0.1828  0.2747  0.3595  0.4337  0.4968  0.5500  0.5943   
0.58         0.0909  0.1802  0.2690  0.3513  0.4238  0.4860  0.5384  0.5823   
0.60         0.0907  0.1779  0.2637  0.3435  0.4142  0.4751  0.5267  0.5701   
0.62         0.0905  0.1758  0.2587  0.3359  0.4047  0.4642  0.5149  0.5575   
0.64         0.0903  0.1738  0.2539  0.3285  0.3952  0.4531  0.5027  0.5446   
0.66         0.0900  0.1720  0.2492  0.3211  0.3856  0.4419  0.4902  0.5311   
0.68         0.0898  0.1700  0.2445  0.3136  0.3757  0.4302  0.4771  0.5170   
0.70         0.0895  0.1680  0.2397  0.3059  0.3656  0.4181  0.4635  0.5021   
0.72         0.0891  0.1658  0.2346  0.2979  0.3550  0.4055  0.4491  0.4865   
0.74         0.0885  0.1632  0.2291  0.2894  0.3438  0.3920  0.4339  0.4698   
0.76         0.0878  0.1602  0.2231  0.2802  0.3319  0.3777  0.4177  0.4519   
0.78         0.0869  0.1568  0.2165  0.2703  0.3190  0.3624  0.4002  0.4327   
0.80         0.0856  0.1526  0.2089  0.2594  0.3051  0.3458  0.3814  0.4120   
0.82         0.0840  0.1476  0.2004  0.2473  0.2898  0.3277  0.3609  0.3896   
0.84         0.0818  0.1417  0.1906  0.2339  0.2730  0.3079  0.3386  0.3651   
0.86         0.0789  0.1345  0.1794  0.2188  0.2544  0.2862  0.3142  0.3385   
0.88         0.0752  0.1260  0.1665  0.2018  0.2337  0.2623  0.2874  0.3093   
0.90         0.0704  0.1158  0.1516  0.1827  0.2107  0.2358  0.2579  0.2772   
0.92         0.0643  0.1036  0.1344  0.1610  0.1849  0.2064  0.2253  0.2418   
0.94         0.0565  0.0892  0.1145  0.1364  0.1560  0.1737  0.1893  0.2028   
0.96         0.0466  0.0721  0.0917  0.1085  0.1236  0.1372  0.1492  0.1597   
0.98         0.0343  0.0518  0.0653  0.0768  0.0872  0.0965  0.104

In [100]:
x = np.array([1.00, 0.5219,0.2464,0.1347,0.1007, 0.0924, 0.0905, 0.0891, 0.0845, 0.0678, 0.00])

In [101]:
x*0.75

array([0.75    , 0.391425, 0.1848  , 0.101025, 0.075525, 0.0693  ,
       0.067875, 0.066825, 0.063375, 0.05085 , 0.      ])

In [104]:
x = np.array([0.2464,0.4346,0.5497,0.6287,0.6869,0.7313,0.7661,0.7937,0.8159,0.8338])
y = np.array([0,0.2464,0.4346,0.5497,0.6287,0.6869,0.7313,0.7661,0.7937,0.8159])
x-y

array([0.2464, 0.1882, 0.1151, 0.079 , 0.0582, 0.0444, 0.0348, 0.0276,
       0.0222, 0.0179])

In [106]:
pos = np.array([100, 90,80,70,60,50,40,30,20,10])

In [109]:
pos*(x-y)*0.75

array([18.48   , 12.7035 ,  6.906  ,  4.1475 ,  2.619  ,  1.665  ,
        1.044  ,  0.621  ,  0.333  ,  0.13425])

In [110]:
sum(pos*(x-y)*0.75)

48.65325

In [111]:
(x-y)*0.75

array([0.1848  , 0.14115 , 0.086325, 0.05925 , 0.04365 , 0.0333  ,
       0.0261  , 0.0207  , 0.01665 , 0.013425])

In [121]:
phi_cd = np.array([1.0,0.9095,0.8250,0.7457,0.6743,0.6126,0.5604,0.5167,0.4805,0.4505,0.4257])

In [140]:
def CDS_numerator(r,dt, Phi):
    Phi_without_last = Phi[0:(len(Phi)-1)]
    Phi_without_0 = Phi[1:]
    t = np.arange(dt, 1+dt, dt)
    #print(t)
    discount = np.exp(-r*t)
    surv = Phi_without_last - Phi_without_0
    #print(surv)
    num_vector = discount*surv
    return(sum(num_vector))

In [141]:
def CDS_denominator(r,dt, Phi):
    Phi_without_last = Phi[0:(len(Phi)-1)]
    Phi_without_0 = Phi[1:]
    t = np.arange(dt, 1+dt, dt)
    discount = np.exp(-r*t)
    surv = Phi_without_0 + Phi_without_last
    num_vector = discount*surv
    return(sum(num_vector))

In [142]:
def CDS_spread(r,dt,Phi,R):
    price = (1-R)*CDS_numerator(r,dt,Phi) / 0.5*dt*CDS_denominator(r,dt,Phi)
    return(price)

In [144]:
CDS_spread(0.1, 0.1, phi_cd,0.5)

0.6805317176128249