In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from math import *
import scipy.stats
from pandas import *
#import scipy.integrate as integrate
from scipy.integrate import quad
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from mpl_toolkits import mplot3d

import plotly.offline as pyoff
import plotly.graph_objs as go
import plotly.graph_objects as go



In [221]:
def jump_distribution_full(x_value,mu,sigma_jump,step_x):
    lower = x_value - step_x/2.0
    upper = x_value + step_x/2.0
    #print(lower,upper)
    def normal_distribution_function(x):
        value = scipy.stats.norm.pdf(x,mu,sigma_jump)
        return value
    res, err = quad(normal_distribution_function, lower, upper)
    return res  #output is a vector of the average densities around the regions of each value in the vector x


In [222]:
x0 = 0.0
xn = 10.0
xsteps = 100
dx = (xn-x0)/xsteps
x = np.arange(x0, xn+dx, dx) #last x value is x = 99 
#print(x,len(x),dx)

In [223]:
t0 = 0.0
tn = 1.0
tsteps = 100
dt = (tn-t0)/tsteps
t = np.arange(t0, tn+dt, dt) #last time value is t = 999.9
r = dt / (dx**2) # ensure r < 1
#print(t,r,len(t),tsteps,dt)

In [224]:
def a_coeff_rs(x_value, sigma, kappa, theta, jump_rate,q_12,q_13):
    coefficient = jump_rate + (sigma**2)/(dx**2) - q_12 - q_13
    return coefficient

def b_coeff_rs(x_value, sigma, kappa, theta, jump_rate):
    #print(sigma,kappa,theta,jump_rate)
    coefficient_2 = 0.5*(sigma**2)*(1/dx**2) + 0.5*(1/dx)*kappa*(theta-x_value)
    #print(coefficient_2)
    return coefficient_2

def c_coeff_rs(x_value, sigma, kappa, theta, jump_rate):
    coefficient_3 = 0.5*(sigma**2)*(1/dx**2) - 0.5*(1/dx)*kappa*(theta-x_value)
    return coefficient_3   

In [225]:
#M_1 = M_matrix(x,0.1,0.7,1.0,1.0)
#M_inv = np.linalg.inv(M_1)
#DataFrame(M_1)

In [226]:
def M_matrix_rs(x,sigma,kappa, theta, jump_rate,q_12, q_13):
    M = np.zeros(shape=(len(x),len(x)))
    M[0,0] = 1.0
    M[len(x)-1, len(x)-1] = 1.0
    
    for i in range(1,(len(x)-1)):
        a_coefficient = a_coeff_rs(x[i], sigma, kappa, theta, jump_rate,q_12,q_13)
        b_coefficient = b_coeff_rs(x[i], sigma, kappa, theta, jump_rate)
        c_coefficient = c_coeff_rs(x[i], sigma, kappa, theta, jump_rate)
        if a_coefficient < 0 or b_coefficient < 0 or c_coefficient <0:
            print('Error')
        M[i,(i-1):(i+2)] = [-dt*c_coefficient, 1+dt*a_coefficient, -dt*b_coefficient]
      
    return M

In [242]:
def M_final_rs(x,sigma_1,sigma_2,kappa_1, kappa_2, theta_1, theta_2,jump_rate, q_12, q_13, q_21, q_23):
    M_f = np.zeros(shape=(len(x),len(x)))
    M_block_1 = M_matrix_rs(x,sigma_1,kappa_1,theta_1,jump_rate,q_12, q_13)
    M_block_2 = M_matrix_rs(x,sigma_2,kappa_2,theta_2,jump_rate,q_21, q_23)
    #print(sigma_2,kappa_2,theta_2,jump_rate,q_21,q_23)
    #print(DataFrame(M_block_2))

    X_1 = np.eye(len(x))*(dt*q_12)
    X_1[0] = 0.0
    X_1[len(x)-1] = 0.0 
    X_2 = np.eye(len(x))*(dt*q_13)
    X_2[0] = 0.0
    X_2[len(x)-1] = 0.0 
    Y_1 = np.eye(len(x))*(dt*q_21)
    Y_1[0] = 0.0
    Y_1[len(x)-1] = 0.0
    Y_2 = np.eye(len(x))*(dt*q_23) 
    Y_2[0] = 0.0
    Y_2[len(x)-1] = 0.0 
    M_final_matrix = np.block([
        [M_block_1, X_1, X_2 ],
        [Y_1, M_block_2 , Y_2],
        [np.zeros((len(x),len(x))), np.zeros((len(x),len(x))), np.eye(len(x))] 
    ])
    return M_final_matrix


In [243]:
test = M_final_rs(x,1,1.5,0.5,0.5,0.5,0.2,0.2,q_12=0.1,q_13=0.1, q_21=0.2, q_23=0.2)
DataFrame(test[len(x):2*len(x),len(x):2*len(x)])

0      1       2      3       4     5    6    7    8    9    ...  91   \
0    1.0000  0.000  0.0000  0.000  0.0000  0.00  0.0  0.0  0.0  0.0  ...  0.0   
1   -1.1225  3.248 -1.1275  0.000  0.0000  0.00  0.0  0.0  0.0  0.0  ...  0.0   
2    0.0000 -1.125  3.2480 -1.125  0.0000  0.00  0.0  0.0  0.0  0.0  ...  0.0   
3    0.0000  0.000 -1.1275  3.248 -1.1225  0.00  0.0  0.0  0.0  0.0  ...  0.0   
4    0.0000  0.000  0.0000 -1.130  3.2480 -1.12  0.0  0.0  0.0  0.0  ...  0.0   
..      ...    ...     ...    ...     ...   ...  ...  ...  ...  ...  ...  ...   
96   0.0000  0.000  0.0000  0.000  0.0000  0.00  0.0  0.0  0.0  0.0  ...  0.0   
97   0.0000  0.000  0.0000  0.000  0.0000  0.00  0.0  0.0  0.0  0.0  ...  0.0   
98   0.0000  0.000  0.0000  0.000  0.0000  0.00  0.0  0.0  0.0  0.0  ...  0.0   
99   0.0000  0.000  0.0000  0.000  0.0000  0.00  0.0  0.0  0.0  0.0  ...  0.0   
100  0.0000  0.000  0.0000  0.000  0.0000  0.00  0.0  0.0  0.0  0.0  ...  0.0   

     92   93   94    95      96     97      98     99      100  
0    0.0  0.0  0.0  0.00  0.0000  0.000  0.0000  0.000  0.0000  
1    0.0  0.0  0.0  0.00  0.0000  0.000  0.0000  0.000  0.0000  
2    0.0  0.0  0.0  0.00  0.0000  0.000  0.0000  0.000  0.0000  
3    0.0  0.0  0.0  0.00  0.0000  0.000  0.0000  0.000  0.0000  
4    0.0  0.0  0.0  0.00  0.0000  0.000  0.0000  0.000  0.0000  
..   ...  ...  ...   ...     ...    ...     ...    ...     ...  
96   0.0  0.0  0.0 -1.36  3.2480 -0.890  0.0000  0.000  0.0000  
97   0.0  0.0  0.0  0.00 -1.3625  3.248 -0.8875  0.000  0.0000  
98   0.0  0.0  0.0  0.00  0.0000 -1.365  3.2480 -0.885  0.0000  
99   0.0  0.0  0.0  0.00  0.0000  0.000 -1.3675  3.248 -0.8825  
100  0.0  0.0  0.0  0.00  0.0000  0.000  0.0000  0.000  1.0000  

[101 rows x 101 columns]

In [244]:
def N_matrix_rs(x, jump_rate, N, mu, sigma_jump, step_x):
    N_m = np.zeros(shape=(len(x),len(x)))
    positions = np.arange(int(-N/2+1),int(N/2),1)
    for i in range(1,(len(x)-1)):
        for j in positions: 
            x_jump = step_x*j
            integral = jump_distribution_full(x_jump, mu, sigma_jump, step_x)
            if (i+j) >= 0 and (i+j) <= (len(x)-1):
                #print(j)
                N_m[i,i+j] = jump_rate*dt*integral
        N_m[i,i] = N_m[i,i]+1
    return N_m

In [245]:
def N_final_rs(x, jump_rate, N,mu,sigma_jump,step_x):
    N_1 = N_matrix_rs(x, jump_rate, N,mu,sigma_jump,step_x)
    N_final_matrix = np.block([
        [N_1, np.zeros((len(x),len(x))), np.zeros((len(x),len(x))) ],
        [np.zeros((len(x),len(x))), N_1, np.zeros((len(x),len(x)))], 
        [np.zeros((len(x),len(x))), np.zeros((len(x),len(x))), np.zeros((len(x),len(x)))]
    ])
    
    return N_final_matrix

In [246]:
N_try = N_final_rs(x, 1.0,4,0.0,0.1,dx)
(N_try[2*len(x):3*len(x),2*len(x):3*len(x)])

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [247]:
#N_try = N_matrix(x, 1.0,4,0.0,0.1,dx)
#DataFrame(N_try[0:10, 0:10])

In [248]:
#def IC_matrix(x, sigma, kappa, theta, jump_rate, mu, sigma_jump, step_x, phi_0, phi_N):
#    b = np.zeros(len(x)-2)
#    B = np.zeros(len(x)-2)
#    b_coefficient = b_coeff(x[1], sigma, kappa, theta, jump_rate)
#    c_coefficient = c_coeff(x[len(x)-2], sigma, kappa, theta, jump_rate)
#    b[0] = c_coefficient*dt*phi_0
#    b[len(x)-3] = b_coefficient*dt*phi_N
    #print(b)
#    jump_0 = jump_distribution_full(-1*dx, mu, sigma_jump, step_x)
#    jump_N = jump_distribution_full(1*dx, mu, sigma_jump, step_x)
#    B[0] = jump_rate*dt*jump_0
#    B[len(x)-3] = jump_rate*dt*jump_N
    
#    IC = b+B
#    return IC

In [249]:
#IC_matrix(x,1,1,1,1,0,1,dx,0,1)

In [250]:
b_1 = np.zeros(len(x))
b_1[len(x)-1] = 1.0
b_2 = np.zeros(len(x))
b_2[len(x)-1] = 1.0
b_3 = np.zeros(len(x))
b = np.block([b_1, b_2, b_3]) 

In [251]:
x_block = np.block([x,x,x])
phi_matrix = np.zeros(shape=(3*len(x),len(t))) 
phi_matrix[:,0] = 1.0 * (x_block > 0.0)
phi_matrix[len(x)-1,:] = 1.0
phi_matrix[2*len(x)-1,:] = 1.0
phi_matrix[(2*len(x)):(3*len(x)),:] = 0.0
#DataFrame(phi_matrix)
#phi_matrix = np.zeros(shape=(len(x), len(t)))
#phi_matrix[:,0] = 1.0 * (x>0.0)
#phi_matrix[len(x)-1,:] = 1.0

In [271]:
q_12 = 0.2
q_13 = 0.1
q_21 = 0.4
q_23 = 0.5
sigma_choice_1 = 5.0
kappa_choice_1 = 7.0
theta_choice_1 = 5.0
sigma_choice_2 = 3.0
kappa_choice_2 = 4.0
theta_choice_2 = 10.0
jump_rate_choice = 2.0
N_choice = 4
mu_choice = 0.0
sigma_jump_choice = 5.0

M = M_final_rs(x,sigma_choice_1,sigma_choice_2, kappa_choice_1, kappa_choice_2,
                theta_choice_1, theta_choice_2, jump_rate_choice, q_12, q_13, q_21, q_23)
#print(DataFrame(M[2*len(x):3*len(x),2*len(x):3*len(x)]))
N_mat = N_final_rs(x, jump_rate = jump_rate_choice, N = N_choice, mu = mu_choice, sigma_jump = sigma_jump_choice, step_x=dx)
print(DataFrame(N_mat[2*len(x):3*len(x),2*len(x):3*len(x)]))
if sigma_choice_1**2 >= np.max(np.abs(dx*kappa_choice_1*(theta_choice_1-x))) and sigma_choice_2**2 >= np.max(np.abs(dx*kappa_choice_2*(theta_choice_2-x))):
    for time in range(1, len(t)): 
        phi_matrix[:,time] = np.linalg.inv(M).dot(N_mat.dot(phi_matrix[:,time-1]) + b)
else:
    print('Stability conditions not satisfied')
    

     0    1    2    3    4    5    6    7    8    9    ...  91   92   93   \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
96   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
97   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
98   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
99   0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
100  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

     94   95   96   97   98   99   100  
0    0.0  0.0  0.0  0.0  0.0  0.0 

In [272]:
accept_x = np.where((x>=0))
accept_x[0]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100], dtype=int64)

In [273]:
phi_matrix[1,]

array([1.        , 0.35594365, 0.26904401, 0.24150829, 0.22718763,
       0.21765687, 0.21039071, 0.20437752, 0.19913486, 0.19440463,
       0.19003695, 0.18593924, 0.18205143, 0.17833299, 0.1747556 ,
       0.17129889, 0.16794785, 0.16469112, 0.16151995, 0.15842744,
       0.15540804, 0.15245723, 0.14957125, 0.14674694, 0.14398156,
       0.14127275, 0.13861842, 0.13601671, 0.13346595, 0.13096459,
       0.12851123, 0.12610455, 0.12374332, 0.12142639, 0.11915266,
       0.11692108, 0.11473065, 0.11258041, 0.11046944, 0.10839684,
       0.10636175, 0.10436333, 0.10240077, 0.10047327, 0.09858008,
       0.09672045, 0.09489366, 0.09309899, 0.09133577, 0.08960333,
       0.08790101, 0.0862282 , 0.08458427, 0.08296863, 0.08138069,
       0.0798199 , 0.0782857 , 0.07677756, 0.07529496, 0.07383739,
       0.07240436, 0.07099539, 0.06961001, 0.06824778, 0.06690825,
       0.06559099, 0.06429558, 0.06302161, 0.06176868, 0.06053641,
       0.05932443, 0.05813235, 0.05695982, 0.05580649, 0.05467

In [274]:
for i in range(len(x),2*len(x)-1):
    print(np.min(phi_matrix[i+1,] - phi_matrix[i,]))

0.26714108377894374
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
-3.137467530855975e-05
-4.9960787642744364e-05
-5.150586468816165e-05
-4.698821075133086e-05
-4.082097009383556e-05
-3.469547035594989e-05
-2.9190523332944807e-05
-2.4439806504794603e-05
-2.0408785869618917e-05
-1.700826174944048e-05
-1.4145675995336227e-05
-1.1774505760397957e-05
-9.773681703517667e-06
-8.075326978662645e-06
-6.637869256920226e-06
-5.461949814100642e-06
-4.452299541157778e-06
-3.594502088866136e-06
-2.904399427405835e-06
-2.3031571049214605e-06
-1.819634845912077e-06
-1.4172102200671333e-06
-1.0811953287115372e-06
-8.208555943856055e-07
-5.995984522222386e-07
-4.383204421642972e-07
-3.036554683255588e-07
-2.089108197544931e-07
-1.358647271354485e-07
-8.360322467648729e-08
-5.058182528383526e-08
-2.673943810815871e-08
-1.3452784441980725e-08
-6.290091669747255e-09
-2.362217754736662e-09
-6.709823807682369e-10
-1.2799217241621363e-10
-1.3311352020650702e-11
-4.04121180963557e-14
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [276]:
def survival(space,time):
    return phi_matrix[space, time]


In [277]:
X = np.arange(0,len(phi_matrix),1)
T = np.arange(0,len(t),1)
X, T = np.meshgrid(X, T)
Phi = survival(X,T)

data=go.Surface(z=Phi, x=x0+dx*X, y=t0+dt*T)

layout = go.Layout(scene = dict(
                    xaxis_title='Initial Position',
                    yaxis_title='Maturity',
                    zaxis_title='Survival Probability'))

fig = go.Figure(data=[data], layout=layout)
pyoff.plot(fig)

'temp-plot.html'

In [1463]:
surv = DataFrame(phi_matrix)

In [31]:
surv['initial_pos'] = x #x0+dx*X[1]

In [32]:
times= DataFrame(t)
time= times[0]

In [33]:
surv.append(time)

0     1     2     3     4     5     6     7     8     9  ...    92  \
0     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
1     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
2     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
3     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
4     0.0  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.00  ...  0.00   
...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
997   1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  ...  1.00   
998   1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  ...  1.00   
999   1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  ...  1.00   
1000  1.0  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.00  ...  1.00   
0     0.0  0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  ...  0.92   

        93    94    95    96    97    98    99  100  initial_pos  
0     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0       -10.00  
1     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0        -9.98  
2     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0        -9.96  
3     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0        -9.94  
4     0.00  0.00  0.00  0.00  0.00  0.00  0.00  0.0        -9.92  
...    ...   ...   ...   ...   ...   ...   ...  ...          ...  
997   1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0         9.94  
998   1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0         9.96  
999   1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0         9.98  
1000  1.00  1.00  1.00  1.00  1.00  1.00  1.00  1.0        10.00  
0     0.93  0.94  0.95  0.96  0.97  0.98  0.99  1.0          NaN  

[1002 rows x 102 columns]

In [34]:
y = np.where((x >= 0.0) & (x<= 1.2))
surv_df_non_zero = surv.iloc[y[0],]
surv_df_non_zero

0         1         2         3         4         5         6  \
501  1.0  0.456936  0.308519  0.247997  0.215148  0.193969  0.178828   
502  1.0  0.702831  0.540755  0.452508  0.398534  0.361864  0.334948   
503  1.0  0.835334  0.701578  0.610614  0.547929  0.502502  0.467902   
504  1.0  0.906826  0.807603  0.726956  0.664857  0.616669  0.578348   
505  1.0  0.945429  0.875271  0.809368  0.753273  0.706698  0.667918   
506  1.0  0.966297  0.917483  0.866032  0.818203  0.775860  0.738933   
507  1.0  0.977589  0.943376  0.904077  0.864714  0.827762  0.794066   
508  1.0  0.983704  0.959053  0.929132  0.897329  0.865910  0.836049   
509  1.0  0.987017  0.968446  0.945368  0.919786  0.893434  0.867458   
510  1.0  0.988810  0.974024  0.955747  0.935003  0.912964  0.890577   
511  1.0  0.989779  0.977311  0.962301  0.945168  0.926617  0.907341   
512  1.0  0.990299  0.979230  0.966395  0.951870  0.936029  0.919328   
513  1.0  0.990575  0.980341  0.968922  0.956236  0.942434  0.927789   
514  1.0  0.990717  0.980974  0.970464  0.959044  0.946737  0.933685   
515  1.0  0.990786  0.981326  0.971390  0.960825  0.949591  0.937741   
516  1.0  0.990815  0.981515  0.971933  0.961936  0.951457  0.940495   
517  1.0  0.990822  0.981607  0.972240  0.962613  0.952654  0.942335   
518  1.0  0.990816  0.981643  0.972402  0.963011  0.953404  0.943543   
519  1.0  0.990803  0.981646  0.972475  0.963231  0.953857  0.944315   
520  1.0  0.990787  0.981629  0.972494  0.963337  0.954114  0.944790   
521  1.0  0.990767  0.981601  0.972479  0.963371  0.954243  0.945064   
522  1.0  0.990747  0.981566  0.972444  0.963360  0.954288  0.945204   
523  1.0  0.990725  0.981527  0.972397  0.963320  0.954279  0.945253   
524  1.0  0.990703  0.981486  0.972343  0.963263  0.954235  0.945243   
525  1.0  0.990681  0.981444  0.972284  0.963195  0.954169  0.945194   
526  1.0  0.990659  0.981400  0.972222  0.963121  0.954089  0.945121   
527  1.0  0.990636  0.981357  0.972160  0.963042  0.954001  0.945032   
528  1.0  0.990614  0.981313  0.972097  0.962963  0.953910  0.944936   
529  1.0  0.990592  0.981270  0.972034  0.962883  0.953817  0.944837   
530  1.0  0.990570  0.981227  0.971972  0.962804  0.953726  0.944739   
531  1.0  0.990548  0.981185  0.971911  0.962728  0.953639  0.944647   
532  1.0  0.990527  0.981144  0.971852  0.962655  0.953557  0.944565   
533  1.0  0.990506  0.981104  0.971796  0.962588  0.953486  0.944499   
534  1.0  0.990486  0.981066  0.971744  0.962528  0.953429  0.944456   
535  1.0  0.990467  0.981030  0.971697  0.962480  0.953392  0.944445   
536  1.0  0.990448  0.980997  0.971659  0.962449  0.953385  0.944480   
537  1.0  0.990431  0.980969  0.971633  0.962443  0.953419  0.944579   
538  1.0  0.990415  0.980949  0.971625  0.962472  0.953513  0.944767   
539  1.0  0.990403  0.980939  0.971645  0.962553  0.953692  0.945078   
540  1.0  0.990395  0.980948  0.971706  0.962711  0.953990  0.945557   
541  1.0  0.990394  0.980984  0.971832  0.962981  0.954457  0.946266   
542  1.0  0.990406  0.981065  0.972053  0.963413  0.955159  0.947285   
543  1.0  0.990439  0.981218  0.972421  0.964078  0.956186  0.948720   
544  1.0  0.990508  0.981484  0.973006  0.965075  0.957657  0.950706   
545  1.0  0.990640  0.981932  0.973915  0.966539  0.959730  0.953413   
546  1.0  0.990882  0.982667  0.975300  0.968655  0.962607  0.957054   
547  1.0  0.991315  0.983850  0.977376  0.971664  0.966541  0.961886   
548  1.0  0.992082  0.985728  0.980436  0.975876  0.971845  0.968216   
549  1.0  0.993435  0.988666  0.984874  0.981680  0.978892  0.976400   
550  1.0  0.995816  0.993186  0.991192  0.989542  0.988115  0.986846   
551  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
552  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
553  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
554  1.0  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
555  1.0  1.000000  1.000000  1.000000  1.00000

In [35]:
accept_t = [0,10,20,30,40,50,60,70,80,90,100]

In [36]:
times = t[accept_t[1:]]
times

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [37]:
output=surv_df_non_zero.iloc[:,accept_t[1:]]
initial_pos = surv['initial_pos'][(surv['initial_pos'] >= 0.0) & (surv['initial_pos'] <= 1.0)]
output['initial_pos'] = initial_pos
survival_values = round(output,4)
survival_values = survival_values.set_index('initial_pos')
#survival_values.columns = t[accept_t]
#output
survival_values

10      20      30      40      50      60      70      80   \
initial_pos                                                                   
0.02         0.1439  0.1072  0.0887  0.0761  0.0667  0.0592  0.0533  0.0485   
0.04         0.2712  0.2029  0.1679  0.1442  0.1263  0.1123  0.1010  0.0919   
0.06         0.3827  0.2879  0.2387  0.2051  0.1798  0.1598  0.1439  0.1309   
0.08         0.4792  0.3633  0.3018  0.2596  0.2277  0.2025  0.1824  0.1661   
0.10         0.5616  0.4299  0.3581  0.3084  0.2707  0.2409  0.2171  0.1978   
0.12         0.6312  0.4884  0.4081  0.3520  0.3093  0.2755  0.2484  0.2264   
0.14         0.6892  0.5397  0.4526  0.3910  0.3439  0.3066  0.2767  0.2524   
0.16         0.7369  0.5844  0.4920  0.4259  0.3751  0.3348  0.3023  0.2761   
0.18         0.7757  0.6232  0.5269  0.4570  0.4031  0.3602  0.3256  0.2976   
0.20         0.8069  0.6566  0.5576  0.4848  0.4283  0.3832  0.3468  0.3173   
0.22         0.8317  0.6853  0.5847  0.5096  0.4509  0.4040  0.3662  0.3354   
0.24         0.8511  0.7099  0.6085  0.5317  0.4714  0.4230  0.3839  0.3521   
0.26         0.8662  0.7307  0.6294  0.5514  0.4898  0.4402  0.4001  0.3675   
0.28         0.8778  0.7483  0.6476  0.5690  0.5064  0.4559  0.4150  0.3818   
0.30         0.8866  0.7631  0.6635  0.5846  0.5214  0.4703  0.4289  0.3951   
0.32         0.8932  0.7754  0.6773  0.5985  0.5350  0.4835  0.4417  0.4077   
0.34         0.8981  0.7856  0.6893  0.6109  0.5473  0.4957  0.4537  0.4195   
0.36         0.9017  0.7941  0.6997  0.6219  0.5585  0.5069  0.4649  0.4306   
0.38         0.9043  0.8010  0.7087  0.6318  0.5688  0.5174  0.4755  0.4413   
0.40         0.9062  0.8067  0.7165  0.6407  0.5783  0.5272  0.4856  0.4516   
0.42         0.9075  0.8113  0.7232  0.6486  0.5870  0.5365  0.4952  0.4615   
0.44         0.9084  0.8151  0.7291  0.6558  0.5951  0.5453  0.5045  0.4712   
0.46         0.9090  0.8181  0.7342  0.6624  0.6028  0.5537  0.5136  0.4808   
0.48         0.9094  0.8205  0.7387  0.6685  0.6100  0.5619  0.5225  0.4902   
0.50         0.9096  0.8226  0.7427  0.6741  0.6169  0.5699  0.5312  0.4997   
0.52         0.9097  0.8242  0.7464  0.6795  0.6237  0.5777  0.5400  0.5091   
0.54         0.9098  0.8256  0.7497  0.6846  0.6303  0.5856  0.5488  0.5187   
0.56         0.9098  0.8269  0.7529  0.6897  0.6369  0.5935  0.5578  0.5285   
0.58         0.9098  0.8280  0.7560  0.6947  0.6436  0.6015  0.5669  0.5386   
0.60         0.9097  0.8291  0.7591  0.6997  0.6504  0.6097  0.5763  0.5490   
0.62         0.9097  0.8303  0.7622  0.7050  0.6574  0.6183  0.5861  0.5598   
0.64         0.9098  0.8316  0.7656  0.7104  0.6648  0.6272  0.5963  0.5710   
0.66         0.9098  0.8330  0.7692  0.7162  0.6725  0.6366  0.6070  0.5828   
0.68         0.9100  0.8347  0.7731  0.7224  0.6807  0.6465  0.6183  0.5953   
0.70         0.9103  0.8367  0.7775  0.7292  0.6895  0.6570  0.6303  0.6084   
0.72         0.9107  0.8391  0.7824  0.7365  0.6990  0.6682  0.6430  0.6223   
0.74         0.9113  0.8419  0.7879  0.7445  0.7092  0.6802  0.6565  0.6371   
0.76         0.9121  0.8453  0.7941  0.7533  0.7202  0.6932  0.6710  0.6528   
0.78         0.9132  0.8493  0.8011  0.7630  0.7322  0.7071  0.6865  0.6696   
0.80         0.9147  0.8540  0.8090  0.7737  0.7453  0.7221  0.7031  0.6876   
0.82         0.9167  0.8597  0.8180  0.7856  0.7596  0.7384  0.7210  0.7068   
0.84         0.9192  0.8663  0.8282  0.7987  0.7751  0.7560  0.7403  0.7274   
0.86         0.9225  0.8741  0.8397  0.8133  0.7922  0.7750  0.7610  0.7495   
0.88         0.9267  0.8832  0.8526  0.8293  0.8108  0.7957  0.7834  0.7733   
0.90         0.9319  0.8937  0.8672  0.8471  0.8311  0.8181  0.8075  0.7989   
0.92         0.9384  0.9059  0.8836  0.8667  0.8533  0.8425  0.8337  0.8264   
0.94         0.9465  0.9200  0.9020  0.8884  0.8777  0.8690  0.8619  0.8561   
0.96         0.9564  0.9362  0.9226  0.9124  0.9043  0.8977  0.8924  0.8880   
0.98         0.9683  0.9548  0.9456  0.9388  0.9334  0.9290  0.925

In [39]:
pd = 1-survival_values
pd

10      20      30      40      50      60      70      80   \
initial_pos                                                                   
0.02         0.8561  0.8928  0.9113  0.9239  0.9333  0.9408  0.9467  0.9515   
0.04         0.7288  0.7971  0.8321  0.8558  0.8737  0.8877  0.8990  0.9081   
0.06         0.6173  0.7121  0.7613  0.7949  0.8202  0.8402  0.8561  0.8691   
0.08         0.5208  0.6367  0.6982  0.7404  0.7723  0.7975  0.8176  0.8339   
0.10         0.4384  0.5701  0.6419  0.6916  0.7293  0.7591  0.7829  0.8022   
0.12         0.3688  0.5116  0.5919  0.6480  0.6907  0.7245  0.7516  0.7736   
0.14         0.3108  0.4603  0.5474  0.6090  0.6561  0.6934  0.7233  0.7476   
0.16         0.2631  0.4156  0.5080  0.5741  0.6249  0.6652  0.6977  0.7239   
0.18         0.2243  0.3768  0.4731  0.5430  0.5969  0.6398  0.6744  0.7024   
0.20         0.1931  0.3434  0.4424  0.5152  0.5717  0.6168  0.6532  0.6827   
0.22         0.1683  0.3147  0.4153  0.4904  0.5491  0.5960  0.6338  0.6646   
0.24         0.1489  0.2901  0.3915  0.4683  0.5286  0.5770  0.6161  0.6479   
0.26         0.1338  0.2693  0.3706  0.4486  0.5102  0.5598  0.5999  0.6325   
0.28         0.1222  0.2517  0.3524  0.4310  0.4936  0.5441  0.5850  0.6182   
0.30         0.1134  0.2369  0.3365  0.4154  0.4786  0.5297  0.5711  0.6049   
0.32         0.1068  0.2246  0.3227  0.4015  0.4650  0.5165  0.5583  0.5923   
0.34         0.1019  0.2144  0.3107  0.3891  0.4527  0.5043  0.5463  0.5805   
0.36         0.0983  0.2059  0.3003  0.3781  0.4415  0.4931  0.5351  0.5694   
0.38         0.0957  0.1990  0.2913  0.3682  0.4312  0.4826  0.5245  0.5587   
0.40         0.0938  0.1933  0.2835  0.3593  0.4217  0.4728  0.5144  0.5484   
0.42         0.0925  0.1887  0.2768  0.3514  0.4130  0.4635  0.5048  0.5385   
0.44         0.0916  0.1849  0.2709  0.3442  0.4049  0.4547  0.4955  0.5288   
0.46         0.0910  0.1819  0.2658  0.3376  0.3972  0.4463  0.4864  0.5192   
0.48         0.0906  0.1795  0.2613  0.3315  0.3900  0.4381  0.4775  0.5098   
0.50         0.0904  0.1774  0.2573  0.3259  0.3831  0.4301  0.4688  0.5003   
0.52         0.0903  0.1758  0.2536  0.3205  0.3763  0.4223  0.4600  0.4909   
0.54         0.0902  0.1744  0.2503  0.3154  0.3697  0.4144  0.4512  0.4813   
0.56         0.0902  0.1731  0.2471  0.3103  0.3631  0.4065  0.4422  0.4715   
0.58         0.0902  0.1720  0.2440  0.3053  0.3564  0.3985  0.4331  0.4614   
0.60         0.0903  0.1709  0.2409  0.3003  0.3496  0.3903  0.4237  0.4510   
0.62         0.0903  0.1697  0.2378  0.2950  0.3426  0.3817  0.4139  0.4402   
0.64         0.0902  0.1684  0.2344  0.2896  0.3352  0.3728  0.4037  0.4290   
0.66         0.0902  0.1670  0.2308  0.2838  0.3275  0.3634  0.3930  0.4172   
0.68         0.0900  0.1653  0.2269  0.2776  0.3193  0.3535  0.3817  0.4047   
0.70         0.0897  0.1633  0.2225  0.2708  0.3105  0.3430  0.3697  0.3916   
0.72         0.0893  0.1609  0.2176  0.2635  0.3010  0.3318  0.3570  0.3777   
0.74         0.0887  0.1581  0.2121  0.2555  0.2908  0.3198  0.3435  0.3629   
0.76         0.0879  0.1547  0.2059  0.2467  0.2798  0.3068  0.3290  0.3472   
0.78         0.0868  0.1507  0.1989  0.2370  0.2678  0.2929  0.3135  0.3304   
0.80         0.0853  0.1460  0.1910  0.2263  0.2547  0.2779  0.2969  0.3124   
0.82         0.0833  0.1403  0.1820  0.2144  0.2404  0.2616  0.2790  0.2932   
0.84         0.0808  0.1337  0.1718  0.2013  0.2249  0.2440  0.2597  0.2726   
0.86         0.0775  0.1259  0.1603  0.1867  0.2078  0.2250  0.2390  0.2505   
0.88         0.0733  0.1168  0.1474  0.1707  0.1892  0.2043  0.2166  0.2267   
0.90         0.0681  0.1063  0.1328  0.1529  0.1689  0.1819  0.1925  0.2011   
0.92         0.0616  0.0941  0.1164  0.1333  0.1467  0.1575  0.1663  0.1736   
0.94         0.0535  0.0800  0.0980  0.1116  0.1223  0.1310  0.1381  0.1439   
0.96         0.0436  0.0638  0.0774  0.0876  0.0957  0.1023  0.1076  0.1120   
0.98         0.0317  0.0452  0.0544  0.0612  0.0666  0.0710  0.074

In [41]:
x = np.array([1.00, 0.4384,0.1931,0.1134,0.0938, 0.0904, 0.0903, 0.0897, 0.0853, 0.0681, 0.00])

In [42]:
x*0.75

array([0.75    , 0.3288  , 0.144825, 0.08505 , 0.07035 , 0.0678  ,
       0.067725, 0.067275, 0.063975, 0.051075, 0.      ])

In [43]:
x = np.array([0.1134,0.2369,0.3365,0.4154,0.4786,0.5297,0.5711,0.6049,0.6323,0.6547])
y = np.array([0,0.1134,0.2369,0.3365,0.4154,0.4786,0.5297,0.5711,0.6049,0.6323])
x-y

array([0.1134, 0.1235, 0.0996, 0.0789, 0.0632, 0.0511, 0.0414, 0.0338,
       0.0274, 0.0224])

In [44]:
pos = np.array([100, 90,80,70,60,50,40,30,20,10])

In [45]:
pos*(x-y)*0.75

array([8.505  , 8.33625, 5.976  , 4.14225, 2.844  , 1.91625, 1.242  ,
       0.7605 , 0.411  , 0.168  ])

In [46]:
sum(pos*(x-y)*0.75)

34.30125

In [36]:
(x-y)*0.75

array([0.0876  , 0.0945  , 0.07485 , 0.058725, 0.0468  , 0.037575,
       0.03045 , 0.024675, 0.0201  , 0.01635 ])